# Generated by Django 3.0.8 on 2021-03-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('graph', models.IntegerField(max_length=200)),
                ('percentage_day_change', models.CharField(max_length=100)),
                ('day_change', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
