export const FETCH_COINS = 'FETCH_COINS'
// export const FETCH_COINS_SUCCESS = 'FETCH_COINS_SUCCESS'
// export const FETCH_COINS_FAILURE = 'FETCH_COINS_FAILURE'

export const FETCH_COIN_DETAILS = 'FETCH_COIN_DETAILS'
export const FETCH_COIN_DETAILS_SUCCESS = 'FETCH_COIN_DETAILS_SUCCESS'
export const FETCH_COIN_DETAILS_FAILURE = 'FETCH_COIN_DETAILS_FAILURE'